/**
 * generated by Xtext 2.39.0
 */
package edu.upb.lp.dearCode.impl;

import edu.upb.lp.dearCode.BucleFor;
import edu.upb.lp.dearCode.DearCodePackage;
import edu.upb.lp.dearCode.Instruccion;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Bucle For</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.dearCode.impl.BucleForImpl#getAccionStop <em>Accion Stop</em>}</li>
 * </ul>
 *
 * @generated
 */
public class BucleForImpl extends InstruccionImpl implements BucleFor
{
  /**
   * The cached value of the '{@link #getAccionStop() <em>Accion Stop</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAccionStop()
   * @generated
   * @ordered
   */
  protected Instruccion accionStop;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BucleForImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DearCodePackage.Literals.BUCLE_FOR;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Instruccion getAccionStop()
  {
    return accionStop;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetAccionStop(Instruccion newAccionStop, NotificationChain msgs)
  {
    Instruccion oldAccionStop = accionStop;
    accionStop = newAccionStop;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, DearCodePackage.BUCLE_FOR__ACCION_STOP, oldAccionStop, newAccionStop);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAccionStop(Instruccion newAccionStop)
  {
    if (newAccionStop != accionStop)
    {
      NotificationChain msgs = null;
      if (accionStop != null)
        msgs = ((InternalEObject)accionStop).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - DearCodePackage.BUCLE_FOR__ACCION_STOP, null, msgs);
      if (newAccionStop != null)
        msgs = ((InternalEObject)newAccionStop).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - DearCodePackage.BUCLE_FOR__ACCION_STOP, null, msgs);
      msgs = basicSetAccionStop(newAccionStop, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DearCodePackage.BUCLE_FOR__ACCION_STOP, newAccionStop, newAccionStop));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case DearCodePackage.BUCLE_FOR__ACCION_STOP:
        return basicSetAccionStop(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DearCodePackage.BUCLE_FOR__ACCION_STOP:
        return getAccionStop();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DearCodePackage.BUCLE_FOR__ACCION_STOP:
        setAccionStop((Instruccion)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DearCodePackage.BUCLE_FOR__ACCION_STOP:
        setAccionStop((Instruccion)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DearCodePackage.BUCLE_FOR__ACCION_STOP:
        return accionStop != null;
    }
    return super.eIsSet(featureID);
  }

} //BucleForImpl
