/**
 * generated by Xtext 2.39.0
 */
package edu.upb.lp.dearCode.impl;

import edu.upb.lp.dearCode.BucleWhile;
import edu.upb.lp.dearCode.DearCodePackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Bucle While</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class BucleWhileImpl extends InstruccionImpl implements BucleWhile
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BucleWhileImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DearCodePackage.Literals.BUCLE_WHILE;
  }

} //BucleWhileImpl
