/**
 * generated by Xtext 2.39.0
 */
package edu.upb.lp.dearCode.impl;

import edu.upb.lp.dearCode.BucleFor;
import edu.upb.lp.dearCode.DearCodePackage;
import edu.upb.lp.dearCode.ElementoBloque;
import edu.upb.lp.dearCode.Expression;
import edu.upb.lp.dearCode.MI_ID;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Bucle For</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.dearCode.impl.BucleForImpl#getVariable <em>Variable</em>}</li>
 *   <li>{@link edu.upb.lp.dearCode.impl.BucleForImpl#getInicio <em>Inicio</em>}</li>
 *   <li>{@link edu.upb.lp.dearCode.impl.BucleForImpl#getFin <em>Fin</em>}</li>
 *   <li>{@link edu.upb.lp.dearCode.impl.BucleForImpl#getPaso <em>Paso</em>}</li>
 *   <li>{@link edu.upb.lp.dearCode.impl.BucleForImpl#getLoopBody <em>Loop Body</em>}</li>
 * </ul>
 *
 * @generated
 */
public class BucleForImpl extends InstruccionImpl implements BucleFor
{
  /**
   * The cached value of the '{@link #getVariable() <em>Variable</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVariable()
   * @generated
   * @ordered
   */
  protected MI_ID variable;

  /**
   * The cached value of the '{@link #getInicio() <em>Inicio</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInicio()
   * @generated
   * @ordered
   */
  protected Expression inicio;

  /**
   * The cached value of the '{@link #getFin() <em>Fin</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFin()
   * @generated
   * @ordered
   */
  protected Expression fin;

  /**
   * The cached value of the '{@link #getPaso() <em>Paso</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPaso()
   * @generated
   * @ordered
   */
  protected Expression paso;

  /**
   * The cached value of the '{@link #getLoopBody() <em>Loop Body</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLoopBody()
   * @generated
   * @ordered
   */
  protected EList<ElementoBloque> loopBody;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected BucleForImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DearCodePackage.Literals.BUCLE_FOR;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public MI_ID getVariable()
  {
    return variable;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetVariable(MI_ID newVariable, NotificationChain msgs)
  {
    MI_ID oldVariable = variable;
    variable = newVariable;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, DearCodePackage.BUCLE_FOR__VARIABLE, oldVariable, newVariable);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setVariable(MI_ID newVariable)
  {
    if (newVariable != variable)
    {
      NotificationChain msgs = null;
      if (variable != null)
        msgs = ((InternalEObject)variable).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - DearCodePackage.BUCLE_FOR__VARIABLE, null, msgs);
      if (newVariable != null)
        msgs = ((InternalEObject)newVariable).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - DearCodePackage.BUCLE_FOR__VARIABLE, null, msgs);
      msgs = basicSetVariable(newVariable, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DearCodePackage.BUCLE_FOR__VARIABLE, newVariable, newVariable));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Expression getInicio()
  {
    return inicio;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetInicio(Expression newInicio, NotificationChain msgs)
  {
    Expression oldInicio = inicio;
    inicio = newInicio;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, DearCodePackage.BUCLE_FOR__INICIO, oldInicio, newInicio);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setInicio(Expression newInicio)
  {
    if (newInicio != inicio)
    {
      NotificationChain msgs = null;
      if (inicio != null)
        msgs = ((InternalEObject)inicio).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - DearCodePackage.BUCLE_FOR__INICIO, null, msgs);
      if (newInicio != null)
        msgs = ((InternalEObject)newInicio).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - DearCodePackage.BUCLE_FOR__INICIO, null, msgs);
      msgs = basicSetInicio(newInicio, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DearCodePackage.BUCLE_FOR__INICIO, newInicio, newInicio));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Expression getFin()
  {
    return fin;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetFin(Expression newFin, NotificationChain msgs)
  {
    Expression oldFin = fin;
    fin = newFin;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, DearCodePackage.BUCLE_FOR__FIN, oldFin, newFin);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setFin(Expression newFin)
  {
    if (newFin != fin)
    {
      NotificationChain msgs = null;
      if (fin != null)
        msgs = ((InternalEObject)fin).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - DearCodePackage.BUCLE_FOR__FIN, null, msgs);
      if (newFin != null)
        msgs = ((InternalEObject)newFin).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - DearCodePackage.BUCLE_FOR__FIN, null, msgs);
      msgs = basicSetFin(newFin, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DearCodePackage.BUCLE_FOR__FIN, newFin, newFin));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Expression getPaso()
  {
    return paso;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetPaso(Expression newPaso, NotificationChain msgs)
  {
    Expression oldPaso = paso;
    paso = newPaso;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, DearCodePackage.BUCLE_FOR__PASO, oldPaso, newPaso);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPaso(Expression newPaso)
  {
    if (newPaso != paso)
    {
      NotificationChain msgs = null;
      if (paso != null)
        msgs = ((InternalEObject)paso).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - DearCodePackage.BUCLE_FOR__PASO, null, msgs);
      if (newPaso != null)
        msgs = ((InternalEObject)newPaso).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - DearCodePackage.BUCLE_FOR__PASO, null, msgs);
      msgs = basicSetPaso(newPaso, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DearCodePackage.BUCLE_FOR__PASO, newPaso, newPaso));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<ElementoBloque> getLoopBody()
  {
    if (loopBody == null)
    {
      loopBody = new EObjectContainmentEList<ElementoBloque>(ElementoBloque.class, this, DearCodePackage.BUCLE_FOR__LOOP_BODY);
    }
    return loopBody;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case DearCodePackage.BUCLE_FOR__VARIABLE:
        return basicSetVariable(null, msgs);
      case DearCodePackage.BUCLE_FOR__INICIO:
        return basicSetInicio(null, msgs);
      case DearCodePackage.BUCLE_FOR__FIN:
        return basicSetFin(null, msgs);
      case DearCodePackage.BUCLE_FOR__PASO:
        return basicSetPaso(null, msgs);
      case DearCodePackage.BUCLE_FOR__LOOP_BODY:
        return ((InternalEList<?>)getLoopBody()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DearCodePackage.BUCLE_FOR__VARIABLE:
        return getVariable();
      case DearCodePackage.BUCLE_FOR__INICIO:
        return getInicio();
      case DearCodePackage.BUCLE_FOR__FIN:
        return getFin();
      case DearCodePackage.BUCLE_FOR__PASO:
        return getPaso();
      case DearCodePackage.BUCLE_FOR__LOOP_BODY:
        return getLoopBody();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DearCodePackage.BUCLE_FOR__VARIABLE:
        setVariable((MI_ID)newValue);
        return;
      case DearCodePackage.BUCLE_FOR__INICIO:
        setInicio((Expression)newValue);
        return;
      case DearCodePackage.BUCLE_FOR__FIN:
        setFin((Expression)newValue);
        return;
      case DearCodePackage.BUCLE_FOR__PASO:
        setPaso((Expression)newValue);
        return;
      case DearCodePackage.BUCLE_FOR__LOOP_BODY:
        getLoopBody().clear();
        getLoopBody().addAll((Collection<? extends ElementoBloque>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DearCodePackage.BUCLE_FOR__VARIABLE:
        setVariable((MI_ID)null);
        return;
      case DearCodePackage.BUCLE_FOR__INICIO:
        setInicio((Expression)null);
        return;
      case DearCodePackage.BUCLE_FOR__FIN:
        setFin((Expression)null);
        return;
      case DearCodePackage.BUCLE_FOR__PASO:
        setPaso((Expression)null);
        return;
      case DearCodePackage.BUCLE_FOR__LOOP_BODY:
        getLoopBody().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DearCodePackage.BUCLE_FOR__VARIABLE:
        return variable != null;
      case DearCodePackage.BUCLE_FOR__INICIO:
        return inicio != null;
      case DearCodePackage.BUCLE_FOR__FIN:
        return fin != null;
      case DearCodePackage.BUCLE_FOR__PASO:
        return paso != null;
      case DearCodePackage.BUCLE_FOR__LOOP_BODY:
        return loopBody != null && !loopBody.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //BucleForImpl
