/**
 * generated by Xtext 2.39.0
 */
package edu.upb.lp.dearCode.impl;

import edu.upb.lp.dearCode.Condicional;
import edu.upb.lp.dearCode.DearCodePackage;
import edu.upb.lp.dearCode.Instruccion;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Condicional</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.dearCode.impl.CondicionalImpl#getAccionElse <em>Accion Else</em>}</li>
 * </ul>
 *
 * @generated
 */
public class CondicionalImpl extends InstruccionImpl implements Condicional
{
  /**
   * The cached value of the '{@link #getAccionElse() <em>Accion Else</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAccionElse()
   * @generated
   * @ordered
   */
  protected Instruccion accionElse;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CondicionalImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DearCodePackage.Literals.CONDICIONAL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Instruccion getAccionElse()
  {
    return accionElse;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetAccionElse(Instruccion newAccionElse, NotificationChain msgs)
  {
    Instruccion oldAccionElse = accionElse;
    accionElse = newAccionElse;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, DearCodePackage.CONDICIONAL__ACCION_ELSE, oldAccionElse, newAccionElse);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAccionElse(Instruccion newAccionElse)
  {
    if (newAccionElse != accionElse)
    {
      NotificationChain msgs = null;
      if (accionElse != null)
        msgs = ((InternalEObject)accionElse).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - DearCodePackage.CONDICIONAL__ACCION_ELSE, null, msgs);
      if (newAccionElse != null)
        msgs = ((InternalEObject)newAccionElse).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - DearCodePackage.CONDICIONAL__ACCION_ELSE, null, msgs);
      msgs = basicSetAccionElse(newAccionElse, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DearCodePackage.CONDICIONAL__ACCION_ELSE, newAccionElse, newAccionElse));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case DearCodePackage.CONDICIONAL__ACCION_ELSE:
        return basicSetAccionElse(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DearCodePackage.CONDICIONAL__ACCION_ELSE:
        return getAccionElse();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DearCodePackage.CONDICIONAL__ACCION_ELSE:
        setAccionElse((Instruccion)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DearCodePackage.CONDICIONAL__ACCION_ELSE:
        setAccionElse((Instruccion)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DearCodePackage.CONDICIONAL__ACCION_ELSE:
        return accionElse != null;
    }
    return super.eIsSet(featureID);
  }

} //CondicionalImpl
