/**
 * generated by Xtext 2.39.0
 */
package edu.upb.lp.dearCode.impl;

import edu.upb.lp.dearCode.DearCodePackage;
import edu.upb.lp.dearCode.Declarar;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Declarar</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.dearCode.impl.DeclararImpl#getVerboDecl <em>Verbo Decl</em>}</li>
 *   <li>{@link edu.upb.lp.dearCode.impl.DeclararImpl#getArticulo <em>Articulo</em>}</li>
 * </ul>
 *
 * @generated
 */
public class DeclararImpl extends InstruccionImpl implements Declarar
{
  /**
   * The default value of the '{@link #getVerboDecl() <em>Verbo Decl</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVerboDecl()
   * @generated
   * @ordered
   */
  protected static final String VERBO_DECL_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getVerboDecl() <em>Verbo Decl</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVerboDecl()
   * @generated
   * @ordered
   */
  protected String verboDecl = VERBO_DECL_EDEFAULT;

  /**
   * The default value of the '{@link #getArticulo() <em>Articulo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getArticulo()
   * @generated
   * @ordered
   */
  protected static final String ARTICULO_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getArticulo() <em>Articulo</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getArticulo()
   * @generated
   * @ordered
   */
  protected String articulo = ARTICULO_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DeclararImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DearCodePackage.Literals.DECLARAR;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getVerboDecl()
  {
    return verboDecl;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setVerboDecl(String newVerboDecl)
  {
    String oldVerboDecl = verboDecl;
    verboDecl = newVerboDecl;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DearCodePackage.DECLARAR__VERBO_DECL, oldVerboDecl, verboDecl));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getArticulo()
  {
    return articulo;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setArticulo(String newArticulo)
  {
    String oldArticulo = articulo;
    articulo = newArticulo;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DearCodePackage.DECLARAR__ARTICULO, oldArticulo, articulo));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DearCodePackage.DECLARAR__VERBO_DECL:
        return getVerboDecl();
      case DearCodePackage.DECLARAR__ARTICULO:
        return getArticulo();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DearCodePackage.DECLARAR__VERBO_DECL:
        setVerboDecl((String)newValue);
        return;
      case DearCodePackage.DECLARAR__ARTICULO:
        setArticulo((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DearCodePackage.DECLARAR__VERBO_DECL:
        setVerboDecl(VERBO_DECL_EDEFAULT);
        return;
      case DearCodePackage.DECLARAR__ARTICULO:
        setArticulo(ARTICULO_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DearCodePackage.DECLARAR__VERBO_DECL:
        return VERBO_DECL_EDEFAULT == null ? verboDecl != null : !VERBO_DECL_EDEFAULT.equals(verboDecl);
      case DearCodePackage.DECLARAR__ARTICULO:
        return ARTICULO_EDEFAULT == null ? articulo != null : !ARTICULO_EDEFAULT.equals(articulo);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (verboDecl: ");
    result.append(verboDecl);
    result.append(", articulo: ");
    result.append(articulo);
    result.append(')');
    return result.toString();
  }

} //DeclararImpl
