/**
 * generated by Xtext 2.39.0
 */
package edu.upb.lp.dearCode.impl;

import edu.upb.lp.dearCode.DearCodePackage;
import edu.upb.lp.dearCode.Funcion;
import edu.upb.lp.dearCode.Instruccion;
import edu.upb.lp.dearCode.MI_ID;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Funcion</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.dearCode.impl.FuncionImpl#getName <em>Name</em>}</li>
 *   <li>{@link edu.upb.lp.dearCode.impl.FuncionImpl#getParametros <em>Parametros</em>}</li>
 *   <li>{@link edu.upb.lp.dearCode.impl.FuncionImpl#getInstrucciones <em>Instrucciones</em>}</li>
 *   <li>{@link edu.upb.lp.dearCode.impl.FuncionImpl#getRetorno <em>Retorno</em>}</li>
 * </ul>
 *
 * @generated
 */
public class FuncionImpl extends InstruccionImpl implements Funcion
{
  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected MI_ID name;

  /**
   * The cached value of the '{@link #getParametros() <em>Parametros</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getParametros()
   * @generated
   * @ordered
   */
  protected EList<MI_ID> parametros;

  /**
   * The cached value of the '{@link #getInstrucciones() <em>Instrucciones</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInstrucciones()
   * @generated
   * @ordered
   */
  protected EList<Instruccion> instrucciones;

  /**
   * The cached value of the '{@link #getRetorno() <em>Retorno</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRetorno()
   * @generated
   * @ordered
   */
  protected MI_ID retorno;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FuncionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DearCodePackage.Literals.FUNCION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public MI_ID getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetName(MI_ID newName, NotificationChain msgs)
  {
    MI_ID oldName = name;
    name = newName;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, DearCodePackage.FUNCION__NAME, oldName, newName);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(MI_ID newName)
  {
    if (newName != name)
    {
      NotificationChain msgs = null;
      if (name != null)
        msgs = ((InternalEObject)name).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - DearCodePackage.FUNCION__NAME, null, msgs);
      if (newName != null)
        msgs = ((InternalEObject)newName).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - DearCodePackage.FUNCION__NAME, null, msgs);
      msgs = basicSetName(newName, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DearCodePackage.FUNCION__NAME, newName, newName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<MI_ID> getParametros()
  {
    if (parametros == null)
    {
      parametros = new EObjectContainmentEList<MI_ID>(MI_ID.class, this, DearCodePackage.FUNCION__PARAMETROS);
    }
    return parametros;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Instruccion> getInstrucciones()
  {
    if (instrucciones == null)
    {
      instrucciones = new EObjectContainmentEList<Instruccion>(Instruccion.class, this, DearCodePackage.FUNCION__INSTRUCCIONES);
    }
    return instrucciones;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public MI_ID getRetorno()
  {
    return retorno;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetRetorno(MI_ID newRetorno, NotificationChain msgs)
  {
    MI_ID oldRetorno = retorno;
    retorno = newRetorno;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, DearCodePackage.FUNCION__RETORNO, oldRetorno, newRetorno);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRetorno(MI_ID newRetorno)
  {
    if (newRetorno != retorno)
    {
      NotificationChain msgs = null;
      if (retorno != null)
        msgs = ((InternalEObject)retorno).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - DearCodePackage.FUNCION__RETORNO, null, msgs);
      if (newRetorno != null)
        msgs = ((InternalEObject)newRetorno).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - DearCodePackage.FUNCION__RETORNO, null, msgs);
      msgs = basicSetRetorno(newRetorno, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, DearCodePackage.FUNCION__RETORNO, newRetorno, newRetorno));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case DearCodePackage.FUNCION__NAME:
        return basicSetName(null, msgs);
      case DearCodePackage.FUNCION__PARAMETROS:
        return ((InternalEList<?>)getParametros()).basicRemove(otherEnd, msgs);
      case DearCodePackage.FUNCION__INSTRUCCIONES:
        return ((InternalEList<?>)getInstrucciones()).basicRemove(otherEnd, msgs);
      case DearCodePackage.FUNCION__RETORNO:
        return basicSetRetorno(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DearCodePackage.FUNCION__NAME:
        return getName();
      case DearCodePackage.FUNCION__PARAMETROS:
        return getParametros();
      case DearCodePackage.FUNCION__INSTRUCCIONES:
        return getInstrucciones();
      case DearCodePackage.FUNCION__RETORNO:
        return getRetorno();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DearCodePackage.FUNCION__NAME:
        setName((MI_ID)newValue);
        return;
      case DearCodePackage.FUNCION__PARAMETROS:
        getParametros().clear();
        getParametros().addAll((Collection<? extends MI_ID>)newValue);
        return;
      case DearCodePackage.FUNCION__INSTRUCCIONES:
        getInstrucciones().clear();
        getInstrucciones().addAll((Collection<? extends Instruccion>)newValue);
        return;
      case DearCodePackage.FUNCION__RETORNO:
        setRetorno((MI_ID)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DearCodePackage.FUNCION__NAME:
        setName((MI_ID)null);
        return;
      case DearCodePackage.FUNCION__PARAMETROS:
        getParametros().clear();
        return;
      case DearCodePackage.FUNCION__INSTRUCCIONES:
        getInstrucciones().clear();
        return;
      case DearCodePackage.FUNCION__RETORNO:
        setRetorno((MI_ID)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DearCodePackage.FUNCION__NAME:
        return name != null;
      case DearCodePackage.FUNCION__PARAMETROS:
        return parametros != null && !parametros.isEmpty();
      case DearCodePackage.FUNCION__INSTRUCCIONES:
        return instrucciones != null && !instrucciones.isEmpty();
      case DearCodePackage.FUNCION__RETORNO:
        return retorno != null;
    }
    return super.eIsSet(featureID);
  }

} //FuncionImpl
