/*
 * generated by Xtext 2.39.0
 */
package edu.upb.lp.parser.antlr;

import com.google.inject.Inject;
import edu.upb.lp.parser.antlr.internal.InternalDearCodeParser;
import edu.upb.lp.services.DearCodeGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class DearCodeParser extends AbstractAntlrParser {

	@Inject
	private DearCodeGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalDearCodeParser createParser(XtextTokenStream stream) {
		return new InternalDearCodeParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Program";
	}

	public DearCodeGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DearCodeGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
