/**
 * generated by Xtext 2.39.0
 */
package edu.upb.lp.dearCode;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Compuesto</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.dearCode.Compuesto#getCantidad <em>Cantidad</em>}</li>
 *   <li>{@link edu.upb.lp.dearCode.Compuesto#getMultiplicador <em>Multiplicador</em>}</li>
 *   <li>{@link edu.upb.lp.dearCode.Compuesto#getResto <em>Resto</em>}</li>
 * </ul>
 *
 * @see edu.upb.lp.dearCode.DearCodePackage#getCompuesto()
 * @model
 * @generated
 */
public interface Compuesto extends NumeroLiteral
{
  /**
   * Returns the value of the '<em><b>Cantidad</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cantidad</em>' containment reference.
   * @see #setCantidad(Simple)
   * @see edu.upb.lp.dearCode.DearCodePackage#getCompuesto_Cantidad()
   * @model containment="true"
   * @generated
   */
  Simple getCantidad();

  /**
   * Sets the value of the '{@link edu.upb.lp.dearCode.Compuesto#getCantidad <em>Cantidad</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Cantidad</em>' containment reference.
   * @see #getCantidad()
   * @generated
   */
  void setCantidad(Simple value);

  /**
   * Returns the value of the '<em><b>Multiplicador</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Multiplicador</em>' attribute.
   * @see #setMultiplicador(String)
   * @see edu.upb.lp.dearCode.DearCodePackage#getCompuesto_Multiplicador()
   * @model
   * @generated
   */
  String getMultiplicador();

  /**
   * Sets the value of the '{@link edu.upb.lp.dearCode.Compuesto#getMultiplicador <em>Multiplicador</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Multiplicador</em>' attribute.
   * @see #getMultiplicador()
   * @generated
   */
  void setMultiplicador(String value);

  /**
   * Returns the value of the '<em><b>Resto</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Resto</em>' containment reference.
   * @see #setResto(Simple)
   * @see edu.upb.lp.dearCode.DearCodePackage#getCompuesto_Resto()
   * @model containment="true"
   * @generated
   */
  Simple getResto();

  /**
   * Sets the value of the '{@link edu.upb.lp.dearCode.Compuesto#getResto <em>Resto</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Resto</em>' containment reference.
   * @see #getResto()
   * @generated
   */
  void setResto(Simple value);

} // Compuesto
