/**
 * generated by Xtext 2.39.0
 */
package edu.upb.lp.dearCode;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Condicional</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.dearCode.Condicional#getCondicion <em>Condicion</em>}</li>
 *   <li>{@link edu.upb.lp.dearCode.Condicional#getInstruccionesThen <em>Instrucciones Then</em>}</li>
 *   <li>{@link edu.upb.lp.dearCode.Condicional#getInstruccionesElse <em>Instrucciones Else</em>}</li>
 * </ul>
 *
 * @see edu.upb.lp.dearCode.DearCodePackage#getCondicional()
 * @model
 * @generated
 */
public interface Condicional extends Instruccion
{
  /**
   * Returns the value of the '<em><b>Condicion</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Condicion</em>' containment reference.
   * @see #setCondicion(Condicion)
   * @see edu.upb.lp.dearCode.DearCodePackage#getCondicional_Condicion()
   * @model containment="true"
   * @generated
   */
  Condicion getCondicion();

  /**
   * Sets the value of the '{@link edu.upb.lp.dearCode.Condicional#getCondicion <em>Condicion</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Condicion</em>' containment reference.
   * @see #getCondicion()
   * @generated
   */
  void setCondicion(Condicion value);

  /**
   * Returns the value of the '<em><b>Instrucciones Then</b></em>' containment reference list.
   * The list contents are of type {@link edu.upb.lp.dearCode.Instruccion}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Instrucciones Then</em>' containment reference list.
   * @see edu.upb.lp.dearCode.DearCodePackage#getCondicional_InstruccionesThen()
   * @model containment="true"
   * @generated
   */
  EList<Instruccion> getInstruccionesThen();

  /**
   * Returns the value of the '<em><b>Instrucciones Else</b></em>' containment reference list.
   * The list contents are of type {@link edu.upb.lp.dearCode.Instruccion}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Instrucciones Else</em>' containment reference list.
   * @see edu.upb.lp.dearCode.DearCodePackage#getCondicional_InstruccionesElse()
   * @model containment="true"
   * @generated
   */
  EList<Instruccion> getInstruccionesElse();

} // Condicional
