/**
 * generated by Xtext 2.39.0
 */
package edu.upb.lp.dearCode;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see edu.upb.lp.dearCode.DearCodeFactory
 * @model kind="package"
 * @generated
 */
public interface DearCodePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "dearCode";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.upb.edu/lp/DearCode";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "dearCode";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  DearCodePackage eINSTANCE = edu.upb.lp.dearCode.impl.DearCodePackageImpl.init();

  /**
   * The meta object id for the '{@link edu.upb.lp.dearCode.impl.ProgramImpl <em>Program</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.dearCode.impl.ProgramImpl
   * @see edu.upb.lp.dearCode.impl.DearCodePackageImpl#getProgram()
   * @generated
   */
  int PROGRAM = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__NAME = 0;

  /**
   * The feature id for the '<em><b>Cartas</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM__CARTAS = 1;

  /**
   * The number of structural features of the '<em>Program</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAM_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link edu.upb.lp.dearCode.impl.CartaImpl <em>Carta</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.dearCode.impl.CartaImpl
   * @see edu.upb.lp.dearCode.impl.DearCodePackageImpl#getCarta()
   * @generated
   */
  int CARTA = 1;

  /**
   * The feature id for the '<em><b>Saludo</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARTA__SALUDO = 0;

  /**
   * The feature id for the '<em><b>Cuerpo</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARTA__CUERPO = 1;

  /**
   * The feature id for the '<em><b>Despedida</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARTA__DESPEDIDA = 2;

  /**
   * The number of structural features of the '<em>Carta</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CARTA_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link edu.upb.lp.dearCode.impl.SaludoImpl <em>Saludo</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.dearCode.impl.SaludoImpl
   * @see edu.upb.lp.dearCode.impl.DearCodePackageImpl#getSaludo()
   * @generated
   */
  int SALUDO = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SALUDO__NAME = 0;

  /**
   * The number of structural features of the '<em>Saludo</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SALUDO_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link edu.upb.lp.dearCode.impl.DespedidaImpl <em>Despedida</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.dearCode.impl.DespedidaImpl
   * @see edu.upb.lp.dearCode.impl.DearCodePackageImpl#getDespedida()
   * @generated
   */
  int DESPEDIDA = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DESPEDIDA__NAME = 0;

  /**
   * The number of structural features of the '<em>Despedida</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DESPEDIDA_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link edu.upb.lp.dearCode.impl.CuerpoImpl <em>Cuerpo</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.dearCode.impl.CuerpoImpl
   * @see edu.upb.lp.dearCode.impl.DearCodePackageImpl#getCuerpo()
   * @generated
   */
  int CUERPO = 4;

  /**
   * The feature id for the '<em><b>Instrucciones</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CUERPO__INSTRUCCIONES = 0;

  /**
   * The number of structural features of the '<em>Cuerpo</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CUERPO_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link edu.upb.lp.dearCode.impl.InstruccionImpl <em>Instruccion</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.dearCode.impl.InstruccionImpl
   * @see edu.upb.lp.dearCode.impl.DearCodePackageImpl#getInstruccion()
   * @generated
   */
  int INSTRUCCION = 5;

  /**
   * The feature id for the '<em><b>Condicion</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTRUCCION__CONDICION = 0;

  /**
   * The feature id for the '<em><b>Accion</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTRUCCION__ACCION = 1;

  /**
   * The number of structural features of the '<em>Instruccion</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTRUCCION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link edu.upb.lp.dearCode.impl.CondicionImpl <em>Condicion</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.dearCode.impl.CondicionImpl
   * @see edu.upb.lp.dearCode.impl.DearCodePackageImpl#getCondicion()
   * @generated
   */
  int CONDICION = 6;

  /**
   * The number of structural features of the '<em>Condicion</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDICION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link edu.upb.lp.dearCode.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.dearCode.impl.ExpressionImpl
   * @see edu.upb.lp.dearCode.impl.DearCodePackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 7;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = CONDICION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link edu.upb.lp.dearCode.impl.IntLiteralImpl <em>Int Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.dearCode.impl.IntLiteralImpl
   * @see edu.upb.lp.dearCode.impl.DearCodePackageImpl#getIntLiteral()
   * @generated
   */
  int INT_LITERAL = 8;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_LITERAL__VALUE = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Int Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_LITERAL_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link edu.upb.lp.dearCode.impl.StringLiteralImpl <em>String Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.dearCode.impl.StringLiteralImpl
   * @see edu.upb.lp.dearCode.impl.DearCodePackageImpl#getStringLiteral()
   * @generated
   */
  int STRING_LITERAL = 9;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_LITERAL__VALUE = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>String Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_LITERAL_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link edu.upb.lp.dearCode.impl.BooleanLiteralImpl <em>Boolean Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.dearCode.impl.BooleanLiteralImpl
   * @see edu.upb.lp.dearCode.impl.DearCodePackageImpl#getBooleanLiteral()
   * @generated
   */
  int BOOLEAN_LITERAL = 10;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN_LITERAL__VALUE = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Boolean Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN_LITERAL_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link edu.upb.lp.dearCode.impl.VariableRefImpl <em>Variable Ref</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.dearCode.impl.VariableRefImpl
   * @see edu.upb.lp.dearCode.impl.DearCodePackageImpl#getVariableRef()
   * @generated
   */
  int VARIABLE_REF = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_REF__NAME = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Variable Ref</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_REF_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link edu.upb.lp.dearCode.impl.CondicionalImpl <em>Condicional</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.dearCode.impl.CondicionalImpl
   * @see edu.upb.lp.dearCode.impl.DearCodePackageImpl#getCondicional()
   * @generated
   */
  int CONDICIONAL = 12;

  /**
   * The feature id for the '<em><b>Condicion</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDICIONAL__CONDICION = INSTRUCCION__CONDICION;

  /**
   * The feature id for the '<em><b>Accion</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDICIONAL__ACCION = INSTRUCCION__ACCION;

  /**
   * The feature id for the '<em><b>Accion Else</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDICIONAL__ACCION_ELSE = INSTRUCCION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Condicional</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDICIONAL_FEATURE_COUNT = INSTRUCCION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link edu.upb.lp.dearCode.impl.BucleWhileImpl <em>Bucle While</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.dearCode.impl.BucleWhileImpl
   * @see edu.upb.lp.dearCode.impl.DearCodePackageImpl#getBucleWhile()
   * @generated
   */
  int BUCLE_WHILE = 13;

  /**
   * The feature id for the '<em><b>Condicion</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUCLE_WHILE__CONDICION = INSTRUCCION__CONDICION;

  /**
   * The feature id for the '<em><b>Accion</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUCLE_WHILE__ACCION = INSTRUCCION__ACCION;

  /**
   * The number of structural features of the '<em>Bucle While</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUCLE_WHILE_FEATURE_COUNT = INSTRUCCION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link edu.upb.lp.dearCode.impl.BucleForImpl <em>Bucle For</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.dearCode.impl.BucleForImpl
   * @see edu.upb.lp.dearCode.impl.DearCodePackageImpl#getBucleFor()
   * @generated
   */
  int BUCLE_FOR = 14;

  /**
   * The feature id for the '<em><b>Condicion</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUCLE_FOR__CONDICION = INSTRUCCION__CONDICION;

  /**
   * The feature id for the '<em><b>Accion</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUCLE_FOR__ACCION = INSTRUCCION__ACCION;

  /**
   * The feature id for the '<em><b>Accion Stop</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUCLE_FOR__ACCION_STOP = INSTRUCCION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Bucle For</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUCLE_FOR_FEATURE_COUNT = INSTRUCCION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link edu.upb.lp.dearCode.impl.OrExprImpl <em>Or Expr</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.dearCode.impl.OrExprImpl
   * @see edu.upb.lp.dearCode.impl.DearCodePackageImpl#getOrExpr()
   * @generated
   */
  int OR_EXPR = 15;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR_EXPR__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR_EXPR__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Or Expr</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR_EXPR_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link edu.upb.lp.dearCode.impl.AndExprImpl <em>And Expr</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.dearCode.impl.AndExprImpl
   * @see edu.upb.lp.dearCode.impl.DearCodePackageImpl#getAndExpr()
   * @generated
   */
  int AND_EXPR = 16;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_EXPR__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_EXPR__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>And Expr</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_EXPR_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link edu.upb.lp.dearCode.impl.EqualityExprImpl <em>Equality Expr</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.dearCode.impl.EqualityExprImpl
   * @see edu.upb.lp.dearCode.impl.DearCodePackageImpl#getEqualityExpr()
   * @generated
   */
  int EQUALITY_EXPR = 17;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQUALITY_EXPR__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQUALITY_EXPR__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Equality Expr</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQUALITY_EXPR_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link edu.upb.lp.dearCode.impl.RelationalExprImpl <em>Relational Expr</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.dearCode.impl.RelationalExprImpl
   * @see edu.upb.lp.dearCode.impl.DearCodePackageImpl#getRelationalExpr()
   * @generated
   */
  int RELATIONAL_EXPR = 18;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATIONAL_EXPR__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATIONAL_EXPR__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Relational Expr</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RELATIONAL_EXPR_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link edu.upb.lp.dearCode.impl.AdditiveExprImpl <em>Additive Expr</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.dearCode.impl.AdditiveExprImpl
   * @see edu.upb.lp.dearCode.impl.DearCodePackageImpl#getAdditiveExpr()
   * @generated
   */
  int ADDITIVE_EXPR = 19;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADDITIVE_EXPR__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADDITIVE_EXPR__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Additive Expr</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADDITIVE_EXPR_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link edu.upb.lp.dearCode.impl.MultiplicativeExprImpl <em>Multiplicative Expr</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.dearCode.impl.MultiplicativeExprImpl
   * @see edu.upb.lp.dearCode.impl.DearCodePackageImpl#getMultiplicativeExpr()
   * @generated
   */
  int MULTIPLICATIVE_EXPR = 20;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLICATIVE_EXPR__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLICATIVE_EXPR__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Multiplicative Expr</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLICATIVE_EXPR_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link edu.upb.lp.dearCode.impl.NotExprImpl <em>Not Expr</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see edu.upb.lp.dearCode.impl.NotExprImpl
   * @see edu.upb.lp.dearCode.impl.DearCodePackageImpl#getNotExpr()
   * @generated
   */
  int NOT_EXPR = 21;

  /**
   * The feature id for the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOT_EXPR__EXPR = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Not Expr</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOT_EXPR_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link edu.upb.lp.dearCode.Program <em>Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Program</em>'.
   * @see edu.upb.lp.dearCode.Program
   * @generated
   */
  EClass getProgram();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.dearCode.Program#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see edu.upb.lp.dearCode.Program#getName()
   * @see #getProgram()
   * @generated
   */
  EAttribute getProgram_Name();

  /**
   * Returns the meta object for the containment reference list '{@link edu.upb.lp.dearCode.Program#getCartas <em>Cartas</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Cartas</em>'.
   * @see edu.upb.lp.dearCode.Program#getCartas()
   * @see #getProgram()
   * @generated
   */
  EReference getProgram_Cartas();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.dearCode.Carta <em>Carta</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Carta</em>'.
   * @see edu.upb.lp.dearCode.Carta
   * @generated
   */
  EClass getCarta();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.dearCode.Carta#getSaludo <em>Saludo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Saludo</em>'.
   * @see edu.upb.lp.dearCode.Carta#getSaludo()
   * @see #getCarta()
   * @generated
   */
  EReference getCarta_Saludo();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.dearCode.Carta#getCuerpo <em>Cuerpo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Cuerpo</em>'.
   * @see edu.upb.lp.dearCode.Carta#getCuerpo()
   * @see #getCarta()
   * @generated
   */
  EReference getCarta_Cuerpo();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.dearCode.Carta#getDespedida <em>Despedida</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Despedida</em>'.
   * @see edu.upb.lp.dearCode.Carta#getDespedida()
   * @see #getCarta()
   * @generated
   */
  EReference getCarta_Despedida();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.dearCode.Saludo <em>Saludo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Saludo</em>'.
   * @see edu.upb.lp.dearCode.Saludo
   * @generated
   */
  EClass getSaludo();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.dearCode.Saludo#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see edu.upb.lp.dearCode.Saludo#getName()
   * @see #getSaludo()
   * @generated
   */
  EAttribute getSaludo_Name();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.dearCode.Despedida <em>Despedida</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Despedida</em>'.
   * @see edu.upb.lp.dearCode.Despedida
   * @generated
   */
  EClass getDespedida();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.dearCode.Despedida#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see edu.upb.lp.dearCode.Despedida#getName()
   * @see #getDespedida()
   * @generated
   */
  EAttribute getDespedida_Name();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.dearCode.Cuerpo <em>Cuerpo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cuerpo</em>'.
   * @see edu.upb.lp.dearCode.Cuerpo
   * @generated
   */
  EClass getCuerpo();

  /**
   * Returns the meta object for the containment reference list '{@link edu.upb.lp.dearCode.Cuerpo#getInstrucciones <em>Instrucciones</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Instrucciones</em>'.
   * @see edu.upb.lp.dearCode.Cuerpo#getInstrucciones()
   * @see #getCuerpo()
   * @generated
   */
  EReference getCuerpo_Instrucciones();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.dearCode.Instruccion <em>Instruccion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Instruccion</em>'.
   * @see edu.upb.lp.dearCode.Instruccion
   * @generated
   */
  EClass getInstruccion();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.dearCode.Instruccion#getCondicion <em>Condicion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condicion</em>'.
   * @see edu.upb.lp.dearCode.Instruccion#getCondicion()
   * @see #getInstruccion()
   * @generated
   */
  EReference getInstruccion_Condicion();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.dearCode.Instruccion#getAccion <em>Accion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Accion</em>'.
   * @see edu.upb.lp.dearCode.Instruccion#getAccion()
   * @see #getInstruccion()
   * @generated
   */
  EReference getInstruccion_Accion();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.dearCode.Condicion <em>Condicion</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Condicion</em>'.
   * @see edu.upb.lp.dearCode.Condicion
   * @generated
   */
  EClass getCondicion();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.dearCode.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see edu.upb.lp.dearCode.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.dearCode.IntLiteral <em>Int Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Int Literal</em>'.
   * @see edu.upb.lp.dearCode.IntLiteral
   * @generated
   */
  EClass getIntLiteral();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.dearCode.IntLiteral#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see edu.upb.lp.dearCode.IntLiteral#getValue()
   * @see #getIntLiteral()
   * @generated
   */
  EAttribute getIntLiteral_Value();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.dearCode.StringLiteral <em>String Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>String Literal</em>'.
   * @see edu.upb.lp.dearCode.StringLiteral
   * @generated
   */
  EClass getStringLiteral();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.dearCode.StringLiteral#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see edu.upb.lp.dearCode.StringLiteral#getValue()
   * @see #getStringLiteral()
   * @generated
   */
  EAttribute getStringLiteral_Value();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.dearCode.BooleanLiteral <em>Boolean Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Boolean Literal</em>'.
   * @see edu.upb.lp.dearCode.BooleanLiteral
   * @generated
   */
  EClass getBooleanLiteral();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.dearCode.BooleanLiteral#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see edu.upb.lp.dearCode.BooleanLiteral#getValue()
   * @see #getBooleanLiteral()
   * @generated
   */
  EAttribute getBooleanLiteral_Value();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.dearCode.VariableRef <em>Variable Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable Ref</em>'.
   * @see edu.upb.lp.dearCode.VariableRef
   * @generated
   */
  EClass getVariableRef();

  /**
   * Returns the meta object for the attribute '{@link edu.upb.lp.dearCode.VariableRef#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see edu.upb.lp.dearCode.VariableRef#getName()
   * @see #getVariableRef()
   * @generated
   */
  EAttribute getVariableRef_Name();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.dearCode.Condicional <em>Condicional</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Condicional</em>'.
   * @see edu.upb.lp.dearCode.Condicional
   * @generated
   */
  EClass getCondicional();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.dearCode.Condicional#getAccionElse <em>Accion Else</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Accion Else</em>'.
   * @see edu.upb.lp.dearCode.Condicional#getAccionElse()
   * @see #getCondicional()
   * @generated
   */
  EReference getCondicional_AccionElse();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.dearCode.BucleWhile <em>Bucle While</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Bucle While</em>'.
   * @see edu.upb.lp.dearCode.BucleWhile
   * @generated
   */
  EClass getBucleWhile();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.dearCode.BucleFor <em>Bucle For</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Bucle For</em>'.
   * @see edu.upb.lp.dearCode.BucleFor
   * @generated
   */
  EClass getBucleFor();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.dearCode.BucleFor#getAccionStop <em>Accion Stop</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Accion Stop</em>'.
   * @see edu.upb.lp.dearCode.BucleFor#getAccionStop()
   * @see #getBucleFor()
   * @generated
   */
  EReference getBucleFor_AccionStop();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.dearCode.OrExpr <em>Or Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Or Expr</em>'.
   * @see edu.upb.lp.dearCode.OrExpr
   * @generated
   */
  EClass getOrExpr();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.dearCode.OrExpr#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see edu.upb.lp.dearCode.OrExpr#getLeft()
   * @see #getOrExpr()
   * @generated
   */
  EReference getOrExpr_Left();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.dearCode.OrExpr#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see edu.upb.lp.dearCode.OrExpr#getRight()
   * @see #getOrExpr()
   * @generated
   */
  EReference getOrExpr_Right();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.dearCode.AndExpr <em>And Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>And Expr</em>'.
   * @see edu.upb.lp.dearCode.AndExpr
   * @generated
   */
  EClass getAndExpr();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.dearCode.AndExpr#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see edu.upb.lp.dearCode.AndExpr#getLeft()
   * @see #getAndExpr()
   * @generated
   */
  EReference getAndExpr_Left();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.dearCode.AndExpr#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see edu.upb.lp.dearCode.AndExpr#getRight()
   * @see #getAndExpr()
   * @generated
   */
  EReference getAndExpr_Right();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.dearCode.EqualityExpr <em>Equality Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Equality Expr</em>'.
   * @see edu.upb.lp.dearCode.EqualityExpr
   * @generated
   */
  EClass getEqualityExpr();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.dearCode.EqualityExpr#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see edu.upb.lp.dearCode.EqualityExpr#getLeft()
   * @see #getEqualityExpr()
   * @generated
   */
  EReference getEqualityExpr_Left();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.dearCode.EqualityExpr#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see edu.upb.lp.dearCode.EqualityExpr#getRight()
   * @see #getEqualityExpr()
   * @generated
   */
  EReference getEqualityExpr_Right();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.dearCode.RelationalExpr <em>Relational Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Relational Expr</em>'.
   * @see edu.upb.lp.dearCode.RelationalExpr
   * @generated
   */
  EClass getRelationalExpr();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.dearCode.RelationalExpr#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see edu.upb.lp.dearCode.RelationalExpr#getLeft()
   * @see #getRelationalExpr()
   * @generated
   */
  EReference getRelationalExpr_Left();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.dearCode.RelationalExpr#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see edu.upb.lp.dearCode.RelationalExpr#getRight()
   * @see #getRelationalExpr()
   * @generated
   */
  EReference getRelationalExpr_Right();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.dearCode.AdditiveExpr <em>Additive Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Additive Expr</em>'.
   * @see edu.upb.lp.dearCode.AdditiveExpr
   * @generated
   */
  EClass getAdditiveExpr();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.dearCode.AdditiveExpr#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see edu.upb.lp.dearCode.AdditiveExpr#getLeft()
   * @see #getAdditiveExpr()
   * @generated
   */
  EReference getAdditiveExpr_Left();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.dearCode.AdditiveExpr#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see edu.upb.lp.dearCode.AdditiveExpr#getRight()
   * @see #getAdditiveExpr()
   * @generated
   */
  EReference getAdditiveExpr_Right();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.dearCode.MultiplicativeExpr <em>Multiplicative Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Multiplicative Expr</em>'.
   * @see edu.upb.lp.dearCode.MultiplicativeExpr
   * @generated
   */
  EClass getMultiplicativeExpr();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.dearCode.MultiplicativeExpr#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see edu.upb.lp.dearCode.MultiplicativeExpr#getLeft()
   * @see #getMultiplicativeExpr()
   * @generated
   */
  EReference getMultiplicativeExpr_Left();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.dearCode.MultiplicativeExpr#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see edu.upb.lp.dearCode.MultiplicativeExpr#getRight()
   * @see #getMultiplicativeExpr()
   * @generated
   */
  EReference getMultiplicativeExpr_Right();

  /**
   * Returns the meta object for class '{@link edu.upb.lp.dearCode.NotExpr <em>Not Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Not Expr</em>'.
   * @see edu.upb.lp.dearCode.NotExpr
   * @generated
   */
  EClass getNotExpr();

  /**
   * Returns the meta object for the containment reference '{@link edu.upb.lp.dearCode.NotExpr#getExpr <em>Expr</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Expr</em>'.
   * @see edu.upb.lp.dearCode.NotExpr#getExpr()
   * @see #getNotExpr()
   * @generated
   */
  EReference getNotExpr_Expr();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  DearCodeFactory getDearCodeFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link edu.upb.lp.dearCode.impl.ProgramImpl <em>Program</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.dearCode.impl.ProgramImpl
     * @see edu.upb.lp.dearCode.impl.DearCodePackageImpl#getProgram()
     * @generated
     */
    EClass PROGRAM = eINSTANCE.getProgram();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PROGRAM__NAME = eINSTANCE.getProgram_Name();

    /**
     * The meta object literal for the '<em><b>Cartas</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAM__CARTAS = eINSTANCE.getProgram_Cartas();

    /**
     * The meta object literal for the '{@link edu.upb.lp.dearCode.impl.CartaImpl <em>Carta</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.dearCode.impl.CartaImpl
     * @see edu.upb.lp.dearCode.impl.DearCodePackageImpl#getCarta()
     * @generated
     */
    EClass CARTA = eINSTANCE.getCarta();

    /**
     * The meta object literal for the '<em><b>Saludo</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CARTA__SALUDO = eINSTANCE.getCarta_Saludo();

    /**
     * The meta object literal for the '<em><b>Cuerpo</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CARTA__CUERPO = eINSTANCE.getCarta_Cuerpo();

    /**
     * The meta object literal for the '<em><b>Despedida</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CARTA__DESPEDIDA = eINSTANCE.getCarta_Despedida();

    /**
     * The meta object literal for the '{@link edu.upb.lp.dearCode.impl.SaludoImpl <em>Saludo</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.dearCode.impl.SaludoImpl
     * @see edu.upb.lp.dearCode.impl.DearCodePackageImpl#getSaludo()
     * @generated
     */
    EClass SALUDO = eINSTANCE.getSaludo();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SALUDO__NAME = eINSTANCE.getSaludo_Name();

    /**
     * The meta object literal for the '{@link edu.upb.lp.dearCode.impl.DespedidaImpl <em>Despedida</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.dearCode.impl.DespedidaImpl
     * @see edu.upb.lp.dearCode.impl.DearCodePackageImpl#getDespedida()
     * @generated
     */
    EClass DESPEDIDA = eINSTANCE.getDespedida();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DESPEDIDA__NAME = eINSTANCE.getDespedida_Name();

    /**
     * The meta object literal for the '{@link edu.upb.lp.dearCode.impl.CuerpoImpl <em>Cuerpo</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.dearCode.impl.CuerpoImpl
     * @see edu.upb.lp.dearCode.impl.DearCodePackageImpl#getCuerpo()
     * @generated
     */
    EClass CUERPO = eINSTANCE.getCuerpo();

    /**
     * The meta object literal for the '<em><b>Instrucciones</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CUERPO__INSTRUCCIONES = eINSTANCE.getCuerpo_Instrucciones();

    /**
     * The meta object literal for the '{@link edu.upb.lp.dearCode.impl.InstruccionImpl <em>Instruccion</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.dearCode.impl.InstruccionImpl
     * @see edu.upb.lp.dearCode.impl.DearCodePackageImpl#getInstruccion()
     * @generated
     */
    EClass INSTRUCCION = eINSTANCE.getInstruccion();

    /**
     * The meta object literal for the '<em><b>Condicion</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INSTRUCCION__CONDICION = eINSTANCE.getInstruccion_Condicion();

    /**
     * The meta object literal for the '<em><b>Accion</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INSTRUCCION__ACCION = eINSTANCE.getInstruccion_Accion();

    /**
     * The meta object literal for the '{@link edu.upb.lp.dearCode.impl.CondicionImpl <em>Condicion</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.dearCode.impl.CondicionImpl
     * @see edu.upb.lp.dearCode.impl.DearCodePackageImpl#getCondicion()
     * @generated
     */
    EClass CONDICION = eINSTANCE.getCondicion();

    /**
     * The meta object literal for the '{@link edu.upb.lp.dearCode.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.dearCode.impl.ExpressionImpl
     * @see edu.upb.lp.dearCode.impl.DearCodePackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '{@link edu.upb.lp.dearCode.impl.IntLiteralImpl <em>Int Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.dearCode.impl.IntLiteralImpl
     * @see edu.upb.lp.dearCode.impl.DearCodePackageImpl#getIntLiteral()
     * @generated
     */
    EClass INT_LITERAL = eINSTANCE.getIntLiteral();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INT_LITERAL__VALUE = eINSTANCE.getIntLiteral_Value();

    /**
     * The meta object literal for the '{@link edu.upb.lp.dearCode.impl.StringLiteralImpl <em>String Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.dearCode.impl.StringLiteralImpl
     * @see edu.upb.lp.dearCode.impl.DearCodePackageImpl#getStringLiteral()
     * @generated
     */
    EClass STRING_LITERAL = eINSTANCE.getStringLiteral();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STRING_LITERAL__VALUE = eINSTANCE.getStringLiteral_Value();

    /**
     * The meta object literal for the '{@link edu.upb.lp.dearCode.impl.BooleanLiteralImpl <em>Boolean Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.dearCode.impl.BooleanLiteralImpl
     * @see edu.upb.lp.dearCode.impl.DearCodePackageImpl#getBooleanLiteral()
     * @generated
     */
    EClass BOOLEAN_LITERAL = eINSTANCE.getBooleanLiteral();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOOLEAN_LITERAL__VALUE = eINSTANCE.getBooleanLiteral_Value();

    /**
     * The meta object literal for the '{@link edu.upb.lp.dearCode.impl.VariableRefImpl <em>Variable Ref</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.dearCode.impl.VariableRefImpl
     * @see edu.upb.lp.dearCode.impl.DearCodePackageImpl#getVariableRef()
     * @generated
     */
    EClass VARIABLE_REF = eINSTANCE.getVariableRef();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE_REF__NAME = eINSTANCE.getVariableRef_Name();

    /**
     * The meta object literal for the '{@link edu.upb.lp.dearCode.impl.CondicionalImpl <em>Condicional</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.dearCode.impl.CondicionalImpl
     * @see edu.upb.lp.dearCode.impl.DearCodePackageImpl#getCondicional()
     * @generated
     */
    EClass CONDICIONAL = eINSTANCE.getCondicional();

    /**
     * The meta object literal for the '<em><b>Accion Else</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONDICIONAL__ACCION_ELSE = eINSTANCE.getCondicional_AccionElse();

    /**
     * The meta object literal for the '{@link edu.upb.lp.dearCode.impl.BucleWhileImpl <em>Bucle While</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.dearCode.impl.BucleWhileImpl
     * @see edu.upb.lp.dearCode.impl.DearCodePackageImpl#getBucleWhile()
     * @generated
     */
    EClass BUCLE_WHILE = eINSTANCE.getBucleWhile();

    /**
     * The meta object literal for the '{@link edu.upb.lp.dearCode.impl.BucleForImpl <em>Bucle For</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.dearCode.impl.BucleForImpl
     * @see edu.upb.lp.dearCode.impl.DearCodePackageImpl#getBucleFor()
     * @generated
     */
    EClass BUCLE_FOR = eINSTANCE.getBucleFor();

    /**
     * The meta object literal for the '<em><b>Accion Stop</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BUCLE_FOR__ACCION_STOP = eINSTANCE.getBucleFor_AccionStop();

    /**
     * The meta object literal for the '{@link edu.upb.lp.dearCode.impl.OrExprImpl <em>Or Expr</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.dearCode.impl.OrExprImpl
     * @see edu.upb.lp.dearCode.impl.DearCodePackageImpl#getOrExpr()
     * @generated
     */
    EClass OR_EXPR = eINSTANCE.getOrExpr();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OR_EXPR__LEFT = eINSTANCE.getOrExpr_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OR_EXPR__RIGHT = eINSTANCE.getOrExpr_Right();

    /**
     * The meta object literal for the '{@link edu.upb.lp.dearCode.impl.AndExprImpl <em>And Expr</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.dearCode.impl.AndExprImpl
     * @see edu.upb.lp.dearCode.impl.DearCodePackageImpl#getAndExpr()
     * @generated
     */
    EClass AND_EXPR = eINSTANCE.getAndExpr();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AND_EXPR__LEFT = eINSTANCE.getAndExpr_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AND_EXPR__RIGHT = eINSTANCE.getAndExpr_Right();

    /**
     * The meta object literal for the '{@link edu.upb.lp.dearCode.impl.EqualityExprImpl <em>Equality Expr</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.dearCode.impl.EqualityExprImpl
     * @see edu.upb.lp.dearCode.impl.DearCodePackageImpl#getEqualityExpr()
     * @generated
     */
    EClass EQUALITY_EXPR = eINSTANCE.getEqualityExpr();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EQUALITY_EXPR__LEFT = eINSTANCE.getEqualityExpr_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EQUALITY_EXPR__RIGHT = eINSTANCE.getEqualityExpr_Right();

    /**
     * The meta object literal for the '{@link edu.upb.lp.dearCode.impl.RelationalExprImpl <em>Relational Expr</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.dearCode.impl.RelationalExprImpl
     * @see edu.upb.lp.dearCode.impl.DearCodePackageImpl#getRelationalExpr()
     * @generated
     */
    EClass RELATIONAL_EXPR = eINSTANCE.getRelationalExpr();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RELATIONAL_EXPR__LEFT = eINSTANCE.getRelationalExpr_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RELATIONAL_EXPR__RIGHT = eINSTANCE.getRelationalExpr_Right();

    /**
     * The meta object literal for the '{@link edu.upb.lp.dearCode.impl.AdditiveExprImpl <em>Additive Expr</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.dearCode.impl.AdditiveExprImpl
     * @see edu.upb.lp.dearCode.impl.DearCodePackageImpl#getAdditiveExpr()
     * @generated
     */
    EClass ADDITIVE_EXPR = eINSTANCE.getAdditiveExpr();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ADDITIVE_EXPR__LEFT = eINSTANCE.getAdditiveExpr_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ADDITIVE_EXPR__RIGHT = eINSTANCE.getAdditiveExpr_Right();

    /**
     * The meta object literal for the '{@link edu.upb.lp.dearCode.impl.MultiplicativeExprImpl <em>Multiplicative Expr</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.dearCode.impl.MultiplicativeExprImpl
     * @see edu.upb.lp.dearCode.impl.DearCodePackageImpl#getMultiplicativeExpr()
     * @generated
     */
    EClass MULTIPLICATIVE_EXPR = eINSTANCE.getMultiplicativeExpr();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MULTIPLICATIVE_EXPR__LEFT = eINSTANCE.getMultiplicativeExpr_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MULTIPLICATIVE_EXPR__RIGHT = eINSTANCE.getMultiplicativeExpr_Right();

    /**
     * The meta object literal for the '{@link edu.upb.lp.dearCode.impl.NotExprImpl <em>Not Expr</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see edu.upb.lp.dearCode.impl.NotExprImpl
     * @see edu.upb.lp.dearCode.impl.DearCodePackageImpl#getNotExpr()
     * @generated
     */
    EClass NOT_EXPR = eINSTANCE.getNotExpr();

    /**
     * The meta object literal for the '<em><b>Expr</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NOT_EXPR__EXPR = eINSTANCE.getNotExpr_Expr();

  }

} //DearCodePackage
