/**
 * generated by Xtext 2.39.0
 */
package edu.upb.lp.dearCode;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Entrada</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.dearCode.Entrada#getVariable <em>Variable</em>}</li>
 * </ul>
 *
 * @see edu.upb.lp.dearCode.DearCodePackage#getEntrada()
 * @model
 * @generated
 */
public interface Entrada extends Instruccion
{
  /**
   * Returns the value of the '<em><b>Variable</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variable</em>' containment reference.
   * @see #setVariable(MI_ID)
   * @see edu.upb.lp.dearCode.DearCodePackage#getEntrada_Variable()
   * @model containment="true"
   * @generated
   */
  MI_ID getVariable();

  /**
   * Sets the value of the '{@link edu.upb.lp.dearCode.Entrada#getVariable <em>Variable</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Variable</em>' containment reference.
   * @see #getVariable()
   * @generated
   */
  void setVariable(MI_ID value);

} // Entrada
