/**
 * generated by Xtext 2.39.0
 */
package edu.upb.lp.dearCode;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Funcion</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.dearCode.Funcion#getName <em>Name</em>}</li>
 *   <li>{@link edu.upb.lp.dearCode.Funcion#getParametros <em>Parametros</em>}</li>
 *   <li>{@link edu.upb.lp.dearCode.Funcion#getInstrucciones <em>Instrucciones</em>}</li>
 *   <li>{@link edu.upb.lp.dearCode.Funcion#getRetorno <em>Retorno</em>}</li>
 * </ul>
 *
 * @see edu.upb.lp.dearCode.DearCodePackage#getFuncion()
 * @model
 * @generated
 */
public interface Funcion extends Instruccion
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' containment reference.
   * @see #setName(MI_ID)
   * @see edu.upb.lp.dearCode.DearCodePackage#getFuncion_Name()
   * @model containment="true"
   * @generated
   */
  MI_ID getName();

  /**
   * Sets the value of the '{@link edu.upb.lp.dearCode.Funcion#getName <em>Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' containment reference.
   * @see #getName()
   * @generated
   */
  void setName(MI_ID value);

  /**
   * Returns the value of the '<em><b>Parametros</b></em>' containment reference list.
   * The list contents are of type {@link edu.upb.lp.dearCode.MI_ID}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parametros</em>' containment reference list.
   * @see edu.upb.lp.dearCode.DearCodePackage#getFuncion_Parametros()
   * @model containment="true"
   * @generated
   */
  EList<MI_ID> getParametros();

  /**
   * Returns the value of the '<em><b>Instrucciones</b></em>' containment reference list.
   * The list contents are of type {@link edu.upb.lp.dearCode.Instruccion}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Instrucciones</em>' containment reference list.
   * @see edu.upb.lp.dearCode.DearCodePackage#getFuncion_Instrucciones()
   * @model containment="true"
   * @generated
   */
  EList<Instruccion> getInstrucciones();

  /**
   * Returns the value of the '<em><b>Retorno</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Retorno</em>' containment reference.
   * @see #setRetorno(MI_ID)
   * @see edu.upb.lp.dearCode.DearCodePackage#getFuncion_Retorno()
   * @model containment="true"
   * @generated
   */
  MI_ID getRetorno();

  /**
   * Sets the value of the '{@link edu.upb.lp.dearCode.Funcion#getRetorno <em>Retorno</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Retorno</em>' containment reference.
   * @see #getRetorno()
   * @generated
   */
  void setRetorno(MI_ID value);

} // Funcion
