/**
 * generated by Xtext 2.39.0
 */
package edu.upb.lp.dearCode;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Return</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link edu.upb.lp.dearCode.Return#getExpresion <em>Expresion</em>}</li>
 * </ul>
 *
 * @see edu.upb.lp.dearCode.DearCodePackage#getReturn()
 * @model
 * @generated
 */
public interface Return extends ElementoBloque
{
  /**
   * Returns the value of the '<em><b>Expresion</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expresion</em>' containment reference.
   * @see #setExpresion(Expression)
   * @see edu.upb.lp.dearCode.DearCodePackage#getReturn_Expresion()
   * @model containment="true"
   * @generated
   */
  Expression getExpresion();

  /**
   * Sets the value of the '{@link edu.upb.lp.dearCode.Return#getExpresion <em>Expresion</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expresion</em>' containment reference.
   * @see #getExpresion()
   * @generated
   */
  void setExpresion(Expression value);

} // Return
